-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE Auto_Insurance (
    months_as_customer INT   NOT NULL,
    age INT   NOT NULL,
    policy_number INT PK   NOT NULL,
    policy_bind_date DATE   NOT NULL,
    policy_state VARCHAR   NOT NULL,
    policy_csl VARCHAR   NOT NULL,
    policy_deductable INT   NOT NULL,
    policy_annual_premium INT   NOT NULL,
    umbrella_limit INT   NOT NULL,
    insured_zip INT   NOT NULL,
    insured_sex VARCHAR   NOT NULL,
    insured_education_level VARCHAR   NOT NULL,
    insured_occupation VARCHAR   NOT NULL,
    insured_hobbies VARCHAR   NOT NULL,
    insured_relationship VARCHAR   NOT NULL,
    capital-gains INT   NOT NULL,
    capital-loss INT   NOT NULL,
    incident_date DATE   NOT NULL,
    incident_type VARCHAR   NOT NULL,
    collision_type VARCHAR   NOT NULL,
    incident_severity VARCHAR   NOT NULL,
    authorities_contacted VARCHAR   NOT NULL,
    incident_state VARCHAR   NOT NULL,
    incident_city VARCHAR   NOT NULL,
    incident_location VARCHAR   NOT NULL,
    incident_hour_of_the_day INT   NOT NULL,
    number_of_vehicles_involved INT   NOT NULL,
    property_damage VARCHAR   NOT NULL,
    bodily_injuries INT   NOT NULL,
    witnesses INT   NOT NULL,
    police_report_available VARCHAR   NOT NULL,
    total_claim_amount INT   NOT NULL,
    injury_claim INT   NOT NULL,
    property_claim INT   NOT NULL,
    vehicle_claim INT   NOT NULL,
    auto_make VARCHAR   NOT NULL,
    auto_model VARCHAR   NOT NULL,
    auto_year INT   NOT NULL,
    fraud_reported VARCHAR   NOT NULL
);

